"""add_must_change_password_to_user

Revision ID: 277136aeaa65
Revises: 9b5af166ab85
Create Date: 2026-07-26 12:17:59.788282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277136aeaa65'
down_revision = '9b5af166ab85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), server_default=sa.text('true'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    # ### end Alembic commands ###
