"""add certification fields to businesses

Revision ID: 661f66885611
Revises: 91c537154e2e
Create Date: 2026-07-30 22:48:07.760216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '661f66885611'
down_revision = '91c537154e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_halal', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('halal_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('has_bpom', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('bpom_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('has_pirt', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('pirt_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('has_nib', sa.Boolean(), nullable=False, server_default='false'))
        batch_op.add_column(sa.Column('nib_number', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.drop_column('nib_number')
        batch_op.drop_column('has_nib')
        batch_op.drop_column('pirt_number')
        batch_op.drop_column('has_pirt')
        batch_op.drop_column('bpom_number')
        batch_op.drop_column('has_bpom')
        batch_op.drop_column('halal_number')
        batch_op.drop_column('has_halal')

    # ### end Alembic commands ###
