"""add category_name quantity unit to expenses

Revision ID: 961ffbb1f622
Revises: f3ea38edc351
Create Date: 2026-07-31 00:11:51.916965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '961ffbb1f622'
down_revision = 'f3ea38edc351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('unit')
        batch_op.drop_column('quantity')
        batch_op.drop_column('category_name')

    # ### end Alembic commands ###
