"""add SalesTransaction SalesTransactionItem and ExpenseTransaction models

Revision ID: e621d13c179a
Revises: 961ffbb1f622
Create Date: 2026-07-31 00:25:33.191619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e621d13c179a'
down_revision = '961ffbb1f622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('transaction_code', sa.String(length=50), nullable=False),
    sa.Column('purpose', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expense_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expense_transactions_transaction_code'), ['transaction_code'], unique=True)

    op.create_table('sales_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('transaction_code', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_transactions_transaction_code'), ['transaction_code'], unique=True)

    op.create_table('sales_transaction_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sales_transaction_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sales_transaction_id'], ['sales_transactions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_transaction_items')
    with op.batch_alter_table('sales_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_transactions_transaction_code'))

    op.drop_table('sales_transactions')
    with op.batch_alter_table('expense_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expense_transactions_transaction_code'))

    op.drop_table('expense_transactions')
    # ### end Alembic commands ###
